title: <p align="center"> Venu Fitratama </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Curriculum Vitae</a>
  </p>

  <p align="center">
  <a href="mailto:venufitratama2@gmail.com">E-mail</a> |
  <a href="https://www.linkedin.com/in/venufitratama/">LinkedIn</a> |
  <a href="https://github.com/venufitratama">GitHub</a>
  </p>
  
  <p align="justify">
  Have great business knowledge, currently pursuing Master Degree of Economics and Business.
  <br>
  Experienced as Business Analyst & Business Development with a strong background in data analysis. Over 3 years of experience in the industry. Proven track record of success in driving business growth and maximizing revenue through data-driven insights and innovative solutions.
  <br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: G-R5M06GESKH # Google Analytics tracking ID
